### ISSUE TITLE
[Feature request] trigger deployment in Squirrel

### ISSUE THREAD

**Issue by lotem** [neolee/SCU#2]
Send a distributed notification named "SquirrelReloadNotification".
This will trigger deployment in future versions of Squirrel.

See diff in main.m for code sending the notification:
https://github.com/lotem/squirrel/commit/62848ce6f2da56d6f5e48413b369d9a52e42ed91

Note that deployment may be time consuming if some of the dictionaries need to be rebuilt. Avoid doing it immediately when every change is made.
Instead, consider adding a button in "General" or "Help" tab. The notice in "Help" tab will still be meaningful to older versions of Squirrel.

**Comment by neolee** [comment]
Got it. Will make it in the next version (0.3).

**Comment by neolee** [comment]
Implemented in the following commit:
https://github.com/neolee/SCU/commit/6fee6bc86db121505204ca07891cb4cd21fdf70c
