### ISSUE TITLE
scu无法升级

### ISSUE THREAD

**Issue by teezybert** [neolee/SCU#4]
在现在的0.2.106版本中 自动更新107无效

**Comment by neolee** [comment]
能否提供更多一点信息？比如如何无法更新？系统版本？

**Comment by teezybert** [comment]
是的 就是每次显示更新之后 确认更新 没有问题， 但是之后就没有用了 再打开软件还是更新前版本 (106)版本

**Comment by neolee** [comment]
很奇异的情况，不过我很快要发布 0.3 版本，届时如果升级还有问题请让我知道，谢谢！
