### ISSUE TITLE
输入方案只能启用没法取消？

### ISSUE THREAD

**Issue by tevino** [neolee/SCU#6]
效果是在启用列打上勾之后没法取消打勾，其他的已打上勾的也没法取消。

是这个功能还没完善吗？

**Comment by neolee** [comment]
非常抱歉，这是我的疏忽导致的 bug，现在已经修正，请使用内置的版本升级功能升级到最新的 0.3.387 版本应该就好了。欢迎报告 bug 和提出建议，谢谢！

**Comment by tevino** [comment]
新版问题解决了。

应该感谢你对开源社区的贡献才是，谢谢 :D
