### ISSUE TITLE
If hotkeys left empty will generate "a" in squirrel.custom.yaml

### ISSUE THREAD

**Issue by littleq0903** [neolee/SCU#7]
as title, if you left a hotkey slot empty, it will be replaced by "a" in configuration.

for example:

```
hotkeys:
    - Shift+Control+grave
    - a
    - a
```

**Comment by neolee** [comment]
A bug in my code. Already fixed in v0.3.389. Please re-download or use built-in update feature to get the newest version. Thanks very much for reporting it.
